modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="pirateur_error"
version="1.0.0"
displayName="pirateur error"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="GERY, MCreator"

[[dependencies.pirateur_error]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.pirateur_error]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

